<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FastEndpoints.Security" Version="5.31.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ModelMatch.Clustering\ModelMatch.Clustering.csproj" />
	  <ProjectReference Include="..\ModelMatch.Matching\ModelMatch.Matching.csproj" />
	  <ProjectReference Include="..\ModelMatch.Project\ModelMatch.Project.csproj" />
	  <ProjectReference Include="..\ModelMatch.User\ModelMatch.User.csproj" />
	</ItemGroup>

</Project>
